# ERROR Handling

Rust中錯誤分爲：可恢復錯誤和不可恢復錯誤，對於可恢復的錯誤：文件未找到等， 不可恢復的錯誤往往都是bug的另一種説法。  可恢復的錯誤類型(Result<T,E>),  不可恢復的錯誤類型(panic!)

## 不可恢復錯誤

程序會在`panic!`宏執行時打印出一段錯誤提示信息，展開並清理當前的調用棧，讓後退出程序

在`std::panic`模块中，包含一些用于停止由panic启动的展开过程的方法

默认情况下，Rust程序会在出现紧急状况时 解开堆栈，若希望立即终止，可以在Cargo.toml中进行配置

```rust
[profile.dev]
panic="abort"
[profile.release]
panic="abort"
```

代价便是牺牲了异常的捕获功能，某种程度上减少了内存

## 可恢復錯誤

```rust
enum Result<T,E>{
	Ok(T),
	Err(E),
}
```

以讀取文件爲例

```rust
use std::fs::File;
fn main(){
let f:u32 =File::open("name.txt");
}

```

此時編譯遇到如下錯誤

```rust
error[E0308]: mismatched types                                                         
 --> src\main.rs:6:16
  |
6 |     let f:u32 =File::open("name.txt");
  |           ---  ^^^^^^^^^^^^^^^^^^^^^^ expected `u32`, found enum `std::result::Result`
  |           |
  |           expected due to this
  |
  = note: expected type `u32`
             found enum `std::result::Result<std::fs::File, std::io::Error>`
```

大致意思為`File::open`結果為Result<T,E>類型，這需要我們對f進行處理，而不是單一的給f指定類型

```rust
let f =File::open("name.txt");
match f{
	Ok(file)=>file,
	Err(error)=>{panic!("open the file has {}",error)},
};
```

```
thread 'main' panicked at 'open the file has 系统找不到指定的文件。 (os error 2)', src\main.rs:10:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\handerr.exe` (exit code: 101)  
```

儅結果為Ok的時候，將Ok變體内部的file值移出，并將這個句柄重新綁定為變量f，執行完成match之後，即可進行f相關的操作

### 匹配不同類型的錯誤

```rust
let f=File::open("hello.txt");
    match f{
        Ok(file)=>file,
        Err(error)=>match error.kind(){
            ErrorKind::NotFound=>match File::create("hello.txt"){
                Ok(fc)=>fc,
                Err(e)=>panic!("Tried to crate file but there was a problem {:?}",e),
            },
            other_err=>panic!("there other problem {:?}",other_err),
        },

    };
```

`io::ErrorKind`由標準庫提供，這是一個枚舉類型，其變體被用於描述io操作所可能導致的不同錯誤。此處的`ErrorKind::NotFound`表示輸入的文件不存在，對`error::kind()`也使用了match表達式，來檢測其返回值是不是`ErrorKind`枚舉中`NotFound`的變體，如果是的話則創建文件，不是則panic

### `unwrap`和`expect`

`unwrap`實現了match表達式的效果，當`Result`的返回值是OK變體時返回ok内部的值，要是Err變體的值時調用panic

```
let f=File::opne("name.txt").unwrap();
```

`expect`,在unwrap的基礎上可以指定panic中的内容，

```rust
let f=File::opne("name.txt").expect("open the file is failed");
```

二者的唯一區別則是： expect觸發panic時會傳入參數字符作爲錯誤信息，而unwrap則是會携帶一段簡短的信息

### 錯誤傳播

將錯誤信息返回給調用者，這個過程就是錯誤傳播

傳播錯誤的快捷方式為`?`

```rust
use std::fs::File;
use std::io;
use std::io::Read;

fn read_file() -> Result<String, io::Error> {
    let mut f = File::open("name.txt")?;
    let mut s = String::new();
    f.read_to_string(&mut s)?;
    Ok(s)
}
```

將`?`置於result之後，如果result的結果為Ok,那麽ok中的值作爲表達式的結果而參與接下來的程序，如果是Err，則會返回。

被`?`運算符所接受的錯誤值會隱式的被`from`函數所處理，當`?`調用from函數時，它就開始嘗試傳入的錯誤類型轉爲當前函數的錯誤類型，并且返回。

```rust
let mut s = String::new();
let mut f = File::open("name.txt")?.read_to_string(&mut s)?;
    
```

`?`運算符只能用於擁有`Result<T,R>`類型的函數

>  ？适用于Result值，如果它是Ok，则将其展开并给出内部值。如果是Err，它将从当前使用的函数返回，
>







