# 自動化測試

## 編寫

Rust中的測試是一個函數，它被用於驗證非測試代碼是否按照預期的方式運行，一般包含3部分

- 準備所需的數據或狀態
- 調用測試的代碼
- 斷言運行結果與期望是否一致

### 測試函數結構

Rust中的測試就是一個標注有`test`屬性的函數，(屬性:用於修飾Rust代碼的元數據)， 測試時，只需要將`#[test]`添加到關鍵字fn的上一行,便可以將函數轉爲測試函數，編寫完成之後，運行`cargo test`來運行測試。

`cargo test`會構建並執行一個用於測試的可執行文件，該文件在執行的過程中會逐一調用所有標注了test屬性的函數，並生成統計測試運行成功或失敗的相關報告。（當構建一個庫時，會自動生成一個測試函數的測試模塊）

```rust
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

`#[test]`將當前的函數標注爲了測試函數，使得該函數在測試運行中被標注出來，而`assert_eq!`則是斷言"2+2"和"4"是否相等。

```rust
E:\mytest\src>cargo test
   Compiling mytest v0.1.0 (E:\mytest)
    Finished test [unoptimized + debuginfo] target(s) in 5.35s
     Running E:\mytest\target\debug\deps\mytest-447963b4ca0f89fc.exe

running 1 test
test tests::it_works ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests mytest

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

- `running 1 test`表明當前執行的1個測試用例,
- `test tests::it_works ... ok`表明在`tests` 測試模塊下的`it_works`測試函數測試成功。
- `test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out`這一行為測試摘要， 統計通過以及失敗的用例的數量
- `Doc-tests mytest`這部分是文檔測試的結果，Rust可以編譯在API文檔中出現的任何代碼實例。

### 文档测试

文档注释使用`markdown`语法书写，支持代码块，Rust注重正确性，这些注释种的代码块也会被编译并且用作测试。

```rust
/// 第一行是对函数的简短描述。
///
/// 接下来数行是详细文档。代码块用三个反引号开启，Rust 会隐式地在其中添加
/// `fn main()` 和 `extern crate <cratename>`。比如测试 `doccomments` crate：
///
///
```

文档测试的主要目的是作为使用函数功能的例子，可以走位完整的代码段被直接使用。





### 另一個測試用例

```rust
#[test]
    fn second_test_works(){panic!("test failed");}
```

結果

```rust
E:\mytest\src>cargo test
   Compiling mytest v0.1.0 (E:\mytest)
    Finished test [unoptimized + debuginfo] target(s) in 2.78s
     Running E:\mytest\target\debug\deps\mytest-447963b4ca0f89fc.exe

running 2 tests
test tests::it_works ... ok
test tests::second_test_works ... FAILED

failures:

---- tests::second_test_works stdout ----
thread 'tests::second_test_works' panicked at 'test failed', src\lib.rs:10:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::second_test_works

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--lib'
```

在Rust中一旦測試函數觸發`panic!`該測試函數就執行失敗，每個測試都獨立的運行在綫程中，主綫程監視測試綫程時，一旦發現測試綫程意外終止，就會將該測試標記為失敗。這也就是第二個測試函數測試失敗的原因。

### assert!

`assert!` 可以接受一個能被計算的bool作爲參數，儅這個值為`true`時，測試通過。當為`false`時，則會調用`panic!` 測試失敗

```rust
pub struct Tnum {
    a:u32,
    b :u32,
}

impl Tnum{
    fn compire(&self)->bool{
        self.a>self.b
    }

}

#[cfg(test)]
mod test_two{
    use super::*;

    #[test]
    fn comp_test(){
        let t=Tnum{a:78,b:32};
        assert!(t.compire());
    }
}
```



`use super::*` test只一個内部模塊，因此需要將外部的模塊中的程序導入到内部模塊中的作用域。

### assert_eq!  assert_ne!

`assert_eq！`，`assert_ne!`斷言兩個參數相等或者不相等，斷言失敗是返回參數值    

```rust
 #[test]
    fn two_nums(){
        let t2=Tnum{a:33,b:17};
        assert_eq!(t2.a,t2.b);
    }
 #[test]
    fn two_nums(){
        let t2=Tnum{a:33,b:17};
        assert_ne!(t2.a,t2.b);
    }
 
```

```

running 3 tests
test test_two::comp_test ... ok
test test_two::two_num ... ok
test test_two::two_nums ... FAILED

failures:

---- test_two::two_nums stdout ----
thread 'test_two::two_nums' panicked at 'assertion failed: `(left == right)`
  left: `33`,
 right: `17`', src\lib.rs:40:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_two::two_nums

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```

### should_panic!

`should_panic`標記這個屬性的測試函數會在代碼發生panic時順利通過，而代碼在不發生panic時執行失敗

```rust
#[cfg(test)]
mod test_two{
    use super::*;

    #[test]
    fn comp_test(){
        let t=Tnum{a:78,b:32};
        assert!(t.compire());
    }
    #[test]
    #[should_panic]
    fn two_nums(){
        let t2=Tnum{a:33,b:17};
        assert_eq!(t2.a,t2.b);
    }

    #[test]
    #[should_panic]
    fn two_num(){
        let t2=Tnum{a:33,b:20};
        assert_ne!(t2.a,t2.b);
    }
}
```

```rust
running 3 tests
test test_two::comp_test ... ok
test test_two::two_num ... FAILED
test test_two::two_nums ... ok

failures:

---- test_two::two_num stdout ----
note: test did not panic as expected

failures:
    test_two::two_num

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```

可以在之後添加`expected`檢查panic發生時輸出的錯誤提示信息是否包含了指定的信息

### Result<T,E>

```rust
mod tests{
    #[test]
    fn f1()->Result<(),String>{
        if 2+2==4{
            Ok(())
        }else {
            Err(String::from("two nums unequal"))
        }
    }
}
```

測試函數的返回值為Result類型，而不是使用`assert_eq!`,在測試通過時返回ok内的(),  測試失敗則會返回Err裏的内容

注:不要再使用Result<T,E>的時候，標注#[should_panic],使用Result的目的是在測試失敗是返回一個err

### 控制測試運行

cargo test 會在測試模式下編譯代碼，并運行生成測試二進制文件

使用`cargo test --help`查看所有可用的命令

```
OPTIONS:
    -q, --quiet                      Display one character per test instead of one line
        --lib                        Test only this package's library unit tests
        --bin <NAME>...              Test only the specified binary
        --bins                       Test all binaries
        --example <NAME>...          Test only the specified example
        --examples                   Test all examples
        --test <NAME>...             Test only the specified test target
        --tests                      Test all tests
        --bench <NAME>...            Test only the specified bench target
        --benches                    Test all benches
        --all-targets                Test all targets
        --doc                        Test only this library's documentation

```

運行多個測試的時，Rust會默認使用多綫程來并行執行，由於測試是同時執行，必須保證測試之間不會相互依賴，或者依賴到同一個環境中。

Rust允許 開發者精確的掌控測試時所啓動的綫程數量，通過二進制文件傳入

`cargo test --test-threads`標記及期望具體的綫程數量

```
cargo test --test-threads=1
```

執行該命令之後，綫程的數量限制為1，即程序不會使用任何的并行操作

### 顯示函數輸出

默認情況下Rust的測試庫，會在測試通過時，捕獲所有的被打印至標準輸出中的消息，即便是調用了`println！`,但只要測試順利通過，他所打印的内容就無法顯示在終端上，只會顯示一條測試通過的消息

只有在測試失敗時，才可以在錯誤提示信息中找到打印至標準輸出中的内容。

```rust
fn fp(a: i32) -> i32 {
    println!("i got a value {}", a);
    10
}

mod testwo {
    use super::*;


    #[test]
    fn f2() {
        let x = fp(1);
        assert_eq!(x,1);
    }
}
```

```
---- testwo::f2 stdout ----
i got a value 1
thread 'testwo::f2' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `1`', src\lib.rs:25:9
note: run with `RUST_BACKTRACE=1` environment variable to display a bac
ktrace


failures:
    testwo::f2

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filte
red out

```

使用`cargo test-- --nocapture`在測試通過時，輸出所捕獲的信息

通過`cargo test `傳入測試名稱來執行需要運行的部分，也可以傳遞模塊名進行測試

### 通過顯示指定忽略某些用例

`ignore`屬性來標記，在`#[test]`標簽下寫入`#[ignore]`忽略測試内容

對於運行忽略的測試内容則`cargo test -- --ignore`

## 測試的組織結構

單元測試：每次運行一個模塊或一個接口

集成測試：獨立於代碼塊之外，通過公共接口，執行一系列測試用例

### 單元測試

目的是將一小段程序單獨隔離出來，從而確定這段程序是否符合預期，將單元測試的程序存放在src下的文件中，為每個源代碼文件都新建一個test模塊，并使用`#[cfg(test)]`進行標注

#### 測試模塊和`#[cfg(test)]`

在tests模塊上標注`#[cfg(test)]`讓rust只在執行cargo test命令時編譯和運行該部分測試程序而執行cargo build是剔除它們。在正常編譯時不包含測試程序，從而節省編譯時間和產出物所佔的空間

`cfg`屬性是配置的縮寫，告知Rust只有處於特定的情況下才可以編譯。

Rust允許測試私有函數

```
fn fp(a: i32) -> i32 {
    println!("i got a value {}", a);
    10
}
mod testwo {
    use super::*;
    #[test]
    fn f2() {
        let x = fp(1);
        assert_eq!(x,1);
    }
}
```

函數fp屬於私有函數(沒有pub關鍵字)，可以對其進行測試

### 集成測試

在Rust中集成測試是，完全位於模塊之外的，只能調用對外公開的接口，目的在于驗證庫的不同部分是否能協同起來正常工作，對於集成測試來説覆蓋率很重要，爲了創建集成測試需要建立一個tests目錄

cargo會到tests目錄下尋找集成測試的文件，在編譯時會將每個文件夾，處理爲一個獨立的包。

```rust
use adder;
#[test]
fn it_works(){
	assert_eq!(4,adder::two(2))
}
```

無需在集成測試中標注`#[cfg(test)]`

也可以在cargo test命令中指定測試函數名稱作爲參數，來運行指定的測試用例，也可以在`cargo test —-`指定文件名，運行指定文件下的測試函數
























